script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - jruby
  - ree
  - rbx
gemfile:
  - gemfiles/activerecord-2.3.gemfile
  - gemfiles/activerecord-3.1.gemfile
  - gemfiles/activerecord-3.2.gemfile
