rvm:
  - 1.8.7
  - 1.9.3
  - jruby
  - ree
  - rbx
gemfile:
  - gemfiles/activerecord_2.3.gemfile
  - gemfiles/activerecord_3.0.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
