# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kasket}
  s.version = "0.8.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mick Staugaard", "Eric Chapweske"]
  s.date = %q{2010-08-24}
  s.description = %q{puts a cap on your queries}
  s.email = %q{mick@staugaard.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "README.rdoc",
     "Rakefile",
     "kasket.gemspec",
     "lib/kasket.rb",
     "lib/kasket/active_record_patches.rb",
     "lib/kasket/configuration_mixin.rb",
     "lib/kasket/dirty_mixin.rb",
     "lib/kasket/query_parser.rb",
     "lib/kasket/read_mixin.rb",
     "lib/kasket/reload_association_mixin.rb",
     "lib/kasket/write_mixin.rb",
     "test/cache_expiry_test.rb",
     "test/configuration_mixin_test.rb",
     "test/database.yml",
     "test/dirty_test.rb",
     "test/find_one_test.rb",
     "test/find_some_test.rb",
     "test/fixtures/blogs.yml",
     "test/fixtures/comments.yml",
     "test/fixtures/posts.yml",
     "test/helper.rb",
     "test/parser_test.rb",
     "test/read_mixin_test.rb",
     "test/test_models.rb",
     "test/transaction_test.rb"
  ]
  s.homepage = %q{http://github.com/staugaard/kasket}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A write back caching layer on active record}
  s.test_files = [
    "test/cache_expiry_test.rb",
     "test/configuration_mixin_test.rb",
     "test/dirty_test.rb",
     "test/find_one_test.rb",
     "test/find_some_test.rb",
     "test/helper.rb",
     "test/parser_test.rb",
     "test/read_mixin_test.rb",
     "test/test_models.rb",
     "test/transaction_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.4"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<temping>, [">= 1.3.0"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.3.4"])
      s.add_dependency(%q<activesupport>, [">= 2.3.4"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<temping>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.3.4"])
    s.add_dependency(%q<activesupport>, [">= 2.3.4"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<temping>, [">= 1.3.0"])
  end
end

